name: Hexo
on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ls -l source/_posts/
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          echo "$DEPLOY_KEY"
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: git config
        env:
          username: simba-fs
          email: simba.fs@gmail.com
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
          git config --global commit.gpgsign true
      - name: Imoport GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Update themes
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Generate hexo
        run: |
          ./script/recorverDate.sh
          hexo generate
      - name: list posts
        run: |
          hexo list post
      - name: Deploy to github.io
        run: |
          hexo deploy
      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{ secrets.BLOG_DEPLOY_KEY }}
          VPS: ${{ secrets.VPS }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          echo "$DEPLOY_KEY"
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $VPS >> ~/.ssh/known_hosts    
      - name: Deploy to vps
        run: |
          git remote add vps ssh://$VPS_USER@$VPS/$VPS_PATH
          cat .git/config
          git push vps master
