name: Hexo
on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          echo "$DEPLOY_KEY"
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 172.104.104.31 >> ~/.ssh/known_hosts
      - name: git config
        env:
          username: simba-fs
          email: simba.fs@gmail.com
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
          git config --global commit.gpgsign true
          
      - name: Imoport GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          
      - name: Update themes
        run: |
          git submodule init
          git submodule update
          
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
          
      - name: Generate and deploy hexo
        run: |
          ./script/recorverDate.sh
          hexo g
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          REMOTE_HOST: simba-fs.dev
          REMOTE_USER: simba
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: "./public/"
          TARGET: /home/simba/website/blog
          
          
          
