name: Hexo
on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          which gpg1
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          echo "$DEPLOY_KEY"
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "simba-fs"
          git config --global user.email "simba.fs@gmail.com"
          echo "$GPG_KEY" > private.key
          gpg --import private.key
          git config --global gpg.program gpg1
          git config --global user.signingkey DD17CEF74242942DC4B09E3E22D857A2BFB0E0AC
          git config --global commit.gpgsign true
      - name: Update themes
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Clean file
        run: |
          hexo clean  
      - name: Generate hexo
        run: |
          hexo generate
      - name: Deploy hexo
        run: |
          hexo deploy
